version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8014:80"
    depends_on:
      - backend
    networks:
      - homalab-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3001:3001"
    volumes:
      - ./backend/apps:/app/apps
      - ./backend/uploads:/app/uploads
      - ./backend/default-assets:/app/default-assets
      - ./backend/settings.json:/app/settings.json
      - ./backend/homelab.db:/app/homelab.db
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - homalab-network
    environment:
      - NODE_ENV=production

networks:
  homalab-network:
    driver: bridge